<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_Delete_Success</name>
   <tag></tag>
   <elementGuidId>223878f0-5197-46f0-9c68-fd6939f4a48d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.oxd-icon.bi-check2.oxd-toast-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='oxd-toaster_1']/div/div/div/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a24a1b17-4b5d-4a3f-b0f5-d8326bd50c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-icon bi-check2 oxd-toast-icon</value>
      <webElementGuid>d17283aa-8bcf-4086-9383-1792ef1e70b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oxd-toaster_1&quot;)/div[@class=&quot;oxd-toast oxd-toast--success oxd-toast-container--toast&quot;]/div[@class=&quot;oxd-toast-start&quot;]/div[@class=&quot;oxd-toast-icon-container&quot;]/div[@class=&quot;oxd-toast-icon-wrap oxd-toast-icon-wrap--success&quot;]/i[@class=&quot;oxd-icon bi-check2 oxd-toast-icon&quot;]</value>
      <webElementGuid>8842d439-4f58-421a-b4f3-5e80b405b039</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='oxd-toaster_1']/div/div/div/div/i</value>
      <webElementGuid>da854c6e-9c8a-4223-98eb-12e22015457b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/i</value>
      <webElementGuid>899b209f-e897-4732-b603-27c83c482f51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
